server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gradingApp?createDatabaseIfNotExist=true
    username: root
    password: ijse
    initialization-mode: always
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true